function report = priority_validation_zero_task(outputRoot)
%PRIORITY_VALIDATION_ZERO_TASK Build an inference-only all-zero input control.
addpath(fullfile(fileparts(fileparts(mfilename('fullpath'))),'pilot_dataset'), ...
    fullfile(fileparts(fileparts(mfilename('fullpath'))),'cell_dataset'),fileparts(mfilename('fullpath')));
sampleId='zero_control'; sampleDir=fullfile(outputRoot,'generated',sampleId);
jsonPath=fullfile(sampleDir,'complete.json');
if isfile(jsonPath), report=jsondecode(fileread(jsonPath)); assert(report.complete); return; end
for folder={sampleDir,fullfile(sampleDir,'sensor_frames'),fullfile(sampleDir,'subsets')}
    if ~isfolder(folder{1}), mkdir(folder{1}); end
end
truth=priority_validation_make_truth('zero',[]);
payload=truth; payload.sample_id=sampleId; payload.scene_id='zero_control'; payload.repeat_index=0;
pilot_atomic_save(fullfile(sampleDir,'prepared.mat'),payload);
for frame=1:10
    framePath=fullfile(sampleDir,'sensor_frames',sprintf('frame_%03d.mat',frame));
    payload=struct('sample_id',sampleId,'frame_index',frame,'sensor_pre_detector',zeros(260,'single'));
    pilot_atomic_save(framePath,payload);
end
payload=struct('sample_id',sampleId,'subset_index',1,'iterations',3, ...
    'input_indices',1:10,'holdout_indices',11:100,'z_um',10:10:100, ...
    'input_physics_mean_float',zeros(260,'single'), ...
    'input_physics_variance_nminus1_float',zeros(260,'single'), ...
    'holdout_physics_mean_float',zeros(260,'single'), ...
    'holdout_physics_variance_nminus1_float',zeros(260,'single'), ...
    'physics_mean_raw',zeros(260,260,10,'single'), ...
    'physics_taylor_raw',zeros(260,260,10,'single'), ...
    'physics_taylor_sqrt_float',zeros(260,260,10,'single'));
pilot_atomic_save(fullfile(sampleDir,'subsets','subset_01.mat'),payload);
report=struct('complete',true,'sample_id',sampleId,'scene_id','zero_control', ...
    'repeat_index',0,'inference_only',true,'target_or_ground_truth_required',false);
cell_write_json(jsonPath,report);
end
