function Reconstruction_newBrain_sparseDepths_it5_100
clear;
close all;
clc;
warning('on');

%% ========================================================================
% 功能
%
% 对以下三个数据集进行稀疏深度重建：
%
% 500_3_fov2
% 650_3_fov1
% 800_2_fov2
%
% 每个 new_rectified\数据集名 文件夹中包含 100 张散斑光场图。
%
% 原版本从 100 张散斑光场图中均匀抽取 20 张进行重建。
% 本版本取消抽样，按照排序后的顺序使用全部 100 张散斑光场图。
%
% 每一张散斑光场图分别在 8 个选定深度上进行重建。
% 同一个 volume_XXX 在 8 个深度文件夹中的结果，共同组成一个
% 稀疏 8 层体积。
%
% 每个数据集最终得到 100 个稀疏 8 层体积。
%
% 输入目录：
%
% 1. 矫正后的 100 张散斑光场图
% D:\xy\20260611_brainSlices_screening\new_rectified\数据集名
%
% 2. uniform / variance 图像
% D:\xy\20260611_brainSlices_screening\
% new_uniform_var_gamma1_small\数据集名
%
% 输出目录：
%
% D:\xy\20260611_brainSlices_screening\
% new_recon_it5_sparse8depths_100volumes
%
% 每个数据集重建：
%
% 1. uniform 图像
% 2. Taylor variance 图像
% 3. 全部 100 张矫正后的散斑光场图
%
% 选定的 35 层序号：
%
% [1, 5, 10, 15, 20, 25, 30, 35]
%
% 对应物理深度：
%
% [-340, -260, -160, -60, 40, 140, 240, 340] um
%
% 对应原始 PSF 索引：
%
% [1, 5, 10, 15, 21, 26, 31, 36]
%
% 迭代次数：
%
% 5
%
% PSF 读取方式：
%
% M_H = matfile(psfHPath);
% H_use = M_H.H(:,:,:,:,指定索引);
%
% M_Ht = matfile(psfHtPath);
% Ht_use = M_Ht.Ht(:,:,:,:,指定索引);
%
% 不完整加载 H 和 Ht，只读取当前需要的单层 PSF。
%% ========================================================================

%% ======================== 1. 总路径 ====================================

rootPath = 'D:\xy\20260611_brainSlices_screening';

rectifiedRoot = fullfile( ...
    rootPath, ...
    'new_rectified' ...
);

uniformVarRoot = fullfile( ...
    rootPath, ...
    'new_uniform_var_gamma1_small' ...
);

saveRoot = fullfile( ...
    rootPath, ...
    'new_recon_it5_sparse8depths_100volumes' ...
);

if ~exist(saveRoot, 'dir')
    mkdir(saveRoot);
end

%% ======================== 2. 指定数据集 ================================

datasetList = {
    '500_3_fov2'
    '650_3_fov1'
    '800_2_fov2'
};

%% ======================== 3. 函数路径 ==================================

codePath = fullfile(rootPath, 'code_used');

addpath(genpath(codePath));
addpath(genpath('D:\xy\Util'));
addpath(genpath('D:\xy\Solver'));

%% ======================== 4. PSF 路径 ==================================

psfHPath = ...
    'F:\xy\20250626-大深度微型系统\合并psf\merged-340_to_340_H.mat';

psfHtPath = ...
    'F:\xy\20250626-大深度微型系统\合并psf\merged-340_to_340_Ht.mat';

if ~exist(psfHPath, 'file')
    error('找不到 H 文件：%s', psfHPath);
end

if ~exist(psfHtPath, 'file')
    error('找不到 Ht 文件：%s', psfHtPath);
end

%% ======================== 5. 输入目录检查 ==============================

if ~exist(rectifiedRoot, 'dir')
    error('找不到矫正图像根目录：%s', rectifiedRoot);
end

if ~exist(uniformVarRoot, 'dir')
    error( ...
        '找不到 uniform / variance 根目录：%s', ...
        uniformVarRoot ...
    );
end

%% ======================== 6. 检查关键函数 ==============================

requiredFunctions = {
    'Reconstruction3D'
    'Reconstruction3D_speckle'
    'backwardProjectGPU'
    'forwardProjectGPU'
    'deconvRL'
};

for i = 1:length(requiredFunctions)

    if isempty(which(requiredFunctions{i}))
        error('找不到函数：%s', requiredFunctions{i});
    end
end

fprintf('\n====================================================\n');
fprintf('当前使用的关键函数\n');
fprintf('====================================================\n');

fprintf( ...
    'Reconstruction3D:          %s\n', ...
    which('Reconstruction3D') ...
);

fprintf( ...
    'Reconstruction3D_speckle: %s\n', ...
    which('Reconstruction3D_speckle') ...
);

fprintf( ...
    'backwardProjectGPU:        %s\n', ...
    which('backwardProjectGPU') ...
);

fprintf( ...
    'forwardProjectGPU:         %s\n', ...
    which('forwardProjectGPU') ...
);

fprintf( ...
    'deconvRL:                  %s\n', ...
    which('deconvRL') ...
);

fprintf( ...
    'matfile:                   %s\n', ...
    which('matfile') ...
);

%% ======================== 7. 重建参数 ==================================

iterNum = 5;

% 每个 LF 文件夹预期包含 100 张散斑光场图
expectedFrameNum = 100;

% true：
% 如果某个 LF 文件夹不是正好 100 张图，则停止该数据集-深度任务。
%
% false：
% 如果数量不是 100，只发出警告，但仍使用该文件夹中的全部图像。
strictFrameCount = true;

% 完整物理深度，共 35 层
depthValueAll = -340:20:340;

% 原始 PSF 文件中的索引
% 原始索引 19 被跳过
psfIndexAll = [1:18, 20:36];

if length(depthValueAll) ~= length(psfIndexAll)
    error('depthValueAll 与 psfIndexAll 长度不一致。');
end

% 本次选定的 8 个深度位置
selectedLayerPositions = [
    1, ...
    5, ...
    10, ...
    15, ...
    20, ...
    25, ...
    30, ...
    35 ...
];

selectedDepthValues = ...
    depthValueAll(selectedLayerPositions);

selectedPSFIndices = ...
    psfIndexAll(selectedLayerPositions);

fprintf('\n====================================================\n');
fprintf('本次选定的深度\n');
fprintf('====================================================\n');

for i = 1:length(selectedLayerPositions)

    fprintf( ...
        ['第 %d / %d 个选定深度：', ...
         '35层序号=%d，物理深度=%+d um，原始PSF索引=%d\n'], ...
        i, ...
        length(selectedLayerPositions), ...
        selectedLayerPositions(i), ...
        selectedDepthValues(i), ...
        selectedPSFIndices(i) ...
    );
end

%% ======================== 8. 运行选项 ==================================

% 是否重建 uniform
runUniform = true;

% 是否重建 Taylor variance
runTaylorVariance = true;

% 是否重建全部 100 张散斑光场图
runAllSingleFrames = true;

% false：
% 如果检测到 TASK_COMPLETED.txt，则跳过该数据集-深度任务。
%
% true：
% 即使已经有完成标记，也重新重建。
overwriteExisting = false;

%% ======================== 9. 日志初始化 ================================

logCell = {
    'dataset', ...
    'selected_depth_number', ...
    'layer_position_in_35', ...
    'physical_depth_um', ...
    'original_psf_index', ...
    'input_frame_number', ...
    'reconstructed_frame_number', ...
    'uniform_status', ...
    'taylor_var_status', ...
    'single_frame_success', ...
    'single_frame_failed', ...
    'task_status', ...
    'message', ...
    'output_path', ...
    'start_time', ...
    'end_time'
};

mappingCell = {
    'dataset', ...
    'volume_sequence', ...
    'original_image_index', ...
    'original_image_name'
};

successTaskNum = 0;
failedTaskNum = 0;
skippedTaskNum = 0;

logBaseName = ...
    'reconstruction_sparse8depths_it5_100volumes_log';

%% ======================== 10. 逐个深度处理 =============================

for depthLoop = 1:length(selectedLayerPositions)

    layerPosition = ...
        selectedLayerPositions(depthLoop);

    physicalDepth = ...
        selectedDepthValues(depthLoop);

    originalPSFIndex = ...
        selectedPSFIndices(depthLoop);

    fprintf('\n\n');
    fprintf('####################################################\n');

    fprintf( ...
        '开始处理第 %d / %d 个选定深度\n', ...
        depthLoop, ...
        length(selectedLayerPositions) ...
    );

    fprintf('35层中的层序号：%d\n', ...
        layerPosition);

    fprintf('物理深度：%+d um\n', ...
        physicalDepth);

    fprintf('原始PSF索引：%d\n', ...
        originalPSFIndex);

    fprintf('####################################################\n');

    %% ------------------ 加载当前单层 PSF -----------------------------

    try
        fprintf('正在加载当前深度单层 PSF...\n');

        [H_use, Ht_use, CAindex_use] = ...
            loadPSFByMatfileRuns( ...
                psfHPath, ...
                psfHtPath, ...
                originalPSFIndex ...
            );

        fprintf('当前深度 PSF 加载完成。\n');

        fprintf( ...
            'H_use 尺寸：%s\n', ...
            mat2str(size(H_use)) ...
        );

        fprintf( ...
            'Ht_use 尺寸：%s\n', ...
            mat2str(size(Ht_use)) ...
        );

        fprintf( ...
            'CAindex_use 尺寸：%s\n', ...
            mat2str(size(CAindex_use)) ...
        );

    catch ME

        fprintf(2, '\n当前深度 PSF 加载失败。\n');

        fprintf(2, ...
            '物理深度：%+d um\n', ...
            physicalDepth ...
        );

        fprintf(2, ...
            '原始PSF索引：%d\n', ...
            originalPSFIndex ...
        );

        fprintf(2, ...
            '错误：%s\n', ...
            ME.message ...
        );

        fprintf(2, ...
            '%s\n', ...
            getReport( ...
                ME, ...
                'extended', ...
                'hyperlinks', ...
                'off' ...
            ) ...
        );

        for datasetIndex = 1:length(datasetList)

            datasetName = ...
                datasetList{datasetIndex};

            taskTime = datetime('now');

            saveDepthRoot = fullfile( ...
                saveRoot, ...
                datasetName, ...
                makeDepthFolderName( ...
                    layerPosition, ...
                    physicalDepth ...
                ) ...
            );

            logCell(end + 1, :) = {
                datasetName, ...
                depthLoop, ...
                layerPosition, ...
                physicalDepth, ...
                originalPSFIndex, ...
                0, ...
                0, ...
                'not_run', ...
                'not_run', ...
                0, ...
                0, ...
                'failed', ...
                ['PSF load failed: ', ME.message], ...
                saveDepthRoot, ...
                char(taskTime), ...
                char(taskTime)
            };

            failedTaskNum = ...
                failedTaskNum + 1;
        end

        saveLogSafely( ...
            logCell, ...
            saveRoot, ...
            logBaseName ...
        );

        continue;
    end

    %% ------------------ 当前深度处理所有数据集 -----------------------

    for datasetIndex = 1:length(datasetList)

        taskStartTime = datetime('now');

        datasetName = ...
            datasetList{datasetIndex};

        fprintf('\n====================================================\n');

        fprintf( ...
            '深度 %d / %d，数据集 %d / %d\n', ...
            depthLoop, ...
            length(selectedLayerPositions), ...
            datasetIndex, ...
            length(datasetList) ...
        );

        fprintf('数据集：%s\n', ...
            datasetName);

        fprintf('物理深度：%+d um\n', ...
            physicalDepth);

        fprintf('====================================================\n');

        %% ---------------- 输入和输出路径 -----------------------------

        rectifiedDatasetPath = fullfile( ...
            rectifiedRoot, ...
            datasetName ...
        );

        uniformVarDatasetPath = fullfile( ...
            uniformVarRoot, ...
            datasetName ...
        );

        saveDatasetRoot = fullfile( ...
            saveRoot, ...
            datasetName ...
        );

        depthFolderName = makeDepthFolderName( ...
            layerPosition, ...
            physicalDepth ...
        );

        saveDepthRoot = fullfile( ...
            saveDatasetRoot, ...
            depthFolderName ...
        );

        saveUniformPath = fullfile( ...
            saveDepthRoot, ...
            'uniform' ...
        );

        saveTaylorPath = fullfile( ...
            saveDepthRoot, ...
            'taylor_var' ...
        );

        saveSingleRoot = fullfile( ...
            saveDepthRoot, ...
            'single_rectified_100' ...
        );

        completedMarkerPath = fullfile( ...
            saveDepthRoot, ...
            'TASK_COMPLETED.txt' ...
        );

        %% ---------------- 检查输入目录 -------------------------------

        if ~exist(rectifiedDatasetPath, 'dir')

            message = sprintf( ...
                'missing rectified dataset: %s', ...
                rectifiedDatasetPath ...
            );

            warning('%s', message);

            taskEndTime = datetime('now');

            logCell(end + 1, :) = {
                datasetName, ...
                depthLoop, ...
                layerPosition, ...
                physicalDepth, ...
                originalPSFIndex, ...
                0, ...
                0, ...
                'not_run', ...
                'not_run', ...
                0, ...
                0, ...
                'failed', ...
                message, ...
                saveDepthRoot, ...
                char(taskStartTime), ...
                char(taskEndTime)
            };

            failedTaskNum = ...
                failedTaskNum + 1;

            continue;
        end

        if ~exist(uniformVarDatasetPath, 'dir')

            warning( ...
                '找不到 uniform / variance 数据集目录：%s', ...
                uniformVarDatasetPath ...
            );
        end

        %% ---------------- 检查完成标记 -------------------------------

        if ~overwriteExisting && ...
                exist(completedMarkerPath, 'file')

            fprintf( ...
                '检测到完成标记，跳过当前数据集-深度任务。\n' ...
            );

            taskEndTime = datetime('now');

            logCell(end + 1, :) = {
                datasetName, ...
                depthLoop, ...
                layerPosition, ...
                physicalDepth, ...
                originalPSFIndex, ...
                0, ...
                0, ...
                'skipped', ...
                'skipped', ...
                0, ...
                0, ...
                'skipped', ...
                'TASK_COMPLETED.txt exists', ...
                saveDepthRoot, ...
                char(taskStartTime), ...
                char(taskEndTime)
            };

            skippedTaskNum = ...
                skippedTaskNum + 1;

            continue;
        end

        %% ---------------- 创建输出目录 -------------------------------

        ensureFolder(saveDatasetRoot);
        ensureFolder(saveDepthRoot);
        ensureFolder(saveUniformPath);
        ensureFolder(saveTaylorPath);
        ensureFolder(saveSingleRoot);

        %% ---------------- 获取全部矫正图像 ---------------------------

        imgList = ...
            getImageList(rectifiedDatasetPath);

        inputFrameNum = ...
            length(imgList);

        if inputFrameNum == 0

            warning( ...
                '没有找到矫正图像：%s', ...
                rectifiedDatasetPath ...
            );

            taskEndTime = datetime('now');

            logCell(end + 1, :) = {
                datasetName, ...
                depthLoop, ...
                layerPosition, ...
                physicalDepth, ...
                originalPSFIndex, ...
                0, ...
                0, ...
                'not_run', ...
                'not_run', ...
                0, ...
                0, ...
                'failed', ...
                'no rectified images', ...
                saveDepthRoot, ...
                char(taskStartTime), ...
                char(taskEndTime)
            };

            failedTaskNum = ...
                failedTaskNum + 1;

            continue;
        end

        %% ---------------- 检查是否为 100 张 --------------------------

        if inputFrameNum ~= expectedFrameNum

            countMessage = sprintf( ...
                ['数据集 %s 检测到 %d 张散斑光场图，', ...
                 '预期数量为 %d 张。'], ...
                datasetName, ...
                inputFrameNum, ...
                expectedFrameNum ...
            );

            if strictFrameCount

                warning( ...
                    '%s 当前数据集-深度任务停止。', ...
                    countMessage ...
                );

                taskEndTime = datetime('now');

                logCell(end + 1, :) = {
                    datasetName, ...
                    depthLoop, ...
                    layerPosition, ...
                    physicalDepth, ...
                    originalPSFIndex, ...
                    inputFrameNum, ...
                    0, ...
                    'not_run', ...
                    'not_run', ...
                    0, ...
                    0, ...
                    'failed', ...
                    countMessage, ...
                    saveDepthRoot, ...
                    char(taskStartTime), ...
                    char(taskEndTime)
                };

                failedTaskNum = ...
                    failedTaskNum + 1;

                continue;

            else

                warning( ...
                    '%s 将使用文件夹内的全部图像。', ...
                    countMessage ...
                );
            end
        end

        %% ---------------- 使用全部图像 -------------------------------

        % 关键修改：
        %
        % 原代码：
        %
        % selectedFrameNum = min(targetFrameNum, inputFrameNum);
        % selectedFrameIndices = makeEvenIndices(...);
        %
        % 现在不再从 100 张中抽取 20 张。
        % 直接使用排序后的全部图像。

        selectedFrameIndices = ...
            1:inputFrameNum;

        selectedFrameNum = ...
            inputFrameNum;

        fprintf( ...
            '输入散斑光场图数量：%d\n', ...
            inputFrameNum ...
        );

        fprintf( ...
            '实际用于重建的数量：%d，全部使用。\n', ...
            selectedFrameNum ...
        );

        %% ---------------- 保存体积对应表 -----------------------------

        datasetMappingCell = {
            'volume_sequence', ...
            'original_image_index', ...
            'original_image_name'
        };

        for frameLoop = 1:selectedFrameNum

            originalFrameIndex = ...
                selectedFrameIndices(frameLoop);

            originalFrameName = ...
                imgList(originalFrameIndex).name;

            datasetMappingCell(end + 1, :) = {
                frameLoop, ...
                originalFrameIndex, ...
                originalFrameName
            };

            % 所有深度使用相同的 100 张图。
            % 总映射表只在第一个深度记录一次。
            if depthLoop == 1

                mappingCell(end + 1, :) = {
                    datasetName, ...
                    frameLoop, ...
                    originalFrameIndex, ...
                    originalFrameName
                };
            end
        end

        % 每个数据集的映射表只保存一次
        if depthLoop == 1

            datasetMappingPath = fullfile( ...
                saveDatasetRoot, ...
                'all_100_volume_mapping.xlsx' ...
            );

            try
                writecell( ...
                    datasetMappingCell, ...
                    datasetMappingPath ...
                );

                fprintf( ...
                    '100 个体积输入映射表已保存：\n%s\n', ...
                    datasetMappingPath ...
                );

            catch ME

                warning( ...
                    '图像对应表保存失败：%s', ...
                    ME.message ...
                );
            end
        end

        %% ---------------- 查找 uniform 文件 --------------------------

        uniformFilePath = findUniformFile( ...
            uniformVarDatasetPath, ...
            datasetName ...
        );

        if isempty(uniformFilePath)

            fprintf(2, ...
                '没有找到 uniform 图像。\n');

        else

            fprintf( ...
                'uniform 输入图像：\n%s\n', ...
                uniformFilePath ...
            );
        end

        %% ---------------- 查找 variance 文件 -------------------------

        varianceFilePath = findVarianceFile( ...
            uniformVarDatasetPath, ...
            datasetName ...
        );

        if isempty(varianceFilePath)

            fprintf(2, ...
                '没有找到 variance 图像。\n');

        else

            fprintf( ...
                'variance 输入图像：\n%s\n', ...
                varianceFilePath ...
            );
        end

        %% ---------------- 初始化任务状态 -----------------------------

        uniformStatus = 'not_run';
        taylorStatus = 'not_run';

        singleSuccessNum = 0;
        singleFailedNum = 0;

        taskMessages = {};

        %% ============================================================
        % 1. uniform 重建
        %% ============================================================

        if runUniform

            if isempty(uniformFilePath)

                uniformStatus = 'failed';

                taskMessages{end + 1} = ...
                    'uniform input not found';

            else

                try
                    fprintf('\n[1/3] 开始重建 uniform\n');

                    uniformInputFolder = ...
                        fileparts(uniformFilePath);

                    uniformInputName = ...
                        getFileNameWithExtension( ...
                            uniformFilePath ...
                        );

                    Reconstruction3D( ...
                        H_use, ...
                        Ht_use, ...
                        CAindex_use, ...
                        addTrailingSeparator( ...
                            uniformInputFolder ...
                        ), ...
                        uniformInputName, ...
                        addTrailingSeparator( ...
                            saveUniformPath ...
                        ), ...
                        iterNum, ...
                        physicalDepth, ...
                        physicalDepth ...
                    );

                    uniformStatus = 'success';

                    fprintf('uniform 重建完成。\n');

                catch ME

                    uniformStatus = 'failed';

                    taskMessages{end + 1} = ...
                        ['uniform failed: ', ME.message];

                    fprintf(2, ...
                        'uniform 重建失败：%s\n', ...
                        ME.message ...
                    );

                    fprintf(2, ...
                        '%s\n', ...
                        getReport( ...
                            ME, ...
                            'extended', ...
                            'hyperlinks', ...
                            'off' ...
                        ) ...
                    );
                end
            end

        else

            uniformStatus = 'disabled';
        end

        %% ============================================================
        % 2. Taylor variance 重建
        %% ============================================================

        if runTaylorVariance

            if isempty(varianceFilePath)

                taylorStatus = 'failed';

                taskMessages{end + 1} = ...
                    'variance input not found';

            else

                try
                    fprintf( ...
                        '\n[2/3] 开始重建 Taylor variance\n' ...
                    );

                    varianceInputFolder = ...
                        fileparts(varianceFilePath);

                    varianceInputName = ...
                        getFileNameWithExtension( ...
                            varianceFilePath ...
                        );

                    % Taylor variance 使用平方 PSF
                    H_squared = H_use .^ 2;
                    Ht_squared = Ht_use .^ 2;

                    Reconstruction3D_speckle( ...
                        H_squared, ...
                        Ht_squared, ...
                        CAindex_use, ...
                        addTrailingSeparator( ...
                            varianceInputFolder ...
                        ), ...
                        varianceInputName, ...
                        addTrailingSeparator( ...
                            saveTaylorPath ...
                        ), ...
                        iterNum, ...
                        physicalDepth, ...
                        physicalDepth ...
                    );

                    clear H_squared Ht_squared;

                    taylorStatus = 'success';

                    fprintf( ...
                        'Taylor variance 重建完成。\n' ...
                    );

                catch ME

                    clear H_squared Ht_squared;

                    taylorStatus = 'failed';

                    taskMessages{end + 1} = ...
                        ['Taylor variance failed: ', ME.message];

                    fprintf(2, ...
                        'Taylor variance 重建失败：%s\n', ...
                        ME.message ...
                    );

                    fprintf(2, ...
                        '%s\n', ...
                        getReport( ...
                            ME, ...
                            'extended', ...
                            'hyperlinks', ...
                            'off' ...
                        ) ...
                    );
                end
            end

        else

            taylorStatus = 'disabled';
        end

        %% ============================================================
        % 3. 全部 100 张散斑光场图重建
        %% ============================================================

        if runAllSingleFrames

            for frameLoop = 1:selectedFrameNum

                originalFrameIndex = ...
                    selectedFrameIndices(frameLoop);

                inputFileName = ...
                    imgList(originalFrameIndex).name;

                % 相同的 volume_XXX 在 8 个深度目录中，
                % 对应同一张散斑光场图的 8 个深度重建结果。
                saveFramePath = fullfile( ...
                    saveSingleRoot, ...
                    sprintf( ...
                        'volume_%03d', ...
                        frameLoop ...
                    ) ...
                );

                if ~exist(saveFramePath, 'dir')
                    mkdir(saveFramePath);
                end

                fprintf( ...
                    '\n[3/3] 体积 %d / %d\n', ...
                    frameLoop, ...
                    selectedFrameNum ...
                );

                fprintf( ...
                    '原始图像序号：%d / %d\n', ...
                    originalFrameIndex, ...
                    inputFrameNum ...
                );

                fprintf( ...
                    '输入文件：%s\n', ...
                    inputFileName ...
                );

                fprintf( ...
                    '输出目录：%s\n', ...
                    saveFramePath ...
                );

                try
                    Reconstruction3D( ...
                        H_use, ...
                        Ht_use, ...
                        CAindex_use, ...
                        addTrailingSeparator( ...
                            rectifiedDatasetPath ...
                        ), ...
                        inputFileName, ...
                        addTrailingSeparator( ...
                            saveFramePath ...
                        ), ...
                        iterNum, ...
                        physicalDepth, ...
                        physicalDepth ...
                    );

                    singleSuccessNum = ...
                        singleSuccessNum + 1;

                catch ME

                    singleFailedNum = ...
                        singleFailedNum + 1;

                    taskMessages{end + 1} = sprintf( ...
                        'volume %d failed: %s', ...
                        frameLoop, ...
                        ME.message ...
                    );

                    fprintf(2, ...
                        '体积 %d 当前深度重建失败：%s\n', ...
                        frameLoop, ...
                        ME.message ...
                    );

                    errorFilePath = fullfile( ...
                        saveFramePath, ...
                        'RECONSTRUCTION_FAILED.txt' ...
                    );

                    errorText = sprintf( ...
                        ['数据集：%s\n', ...
                         '35层序号：%d\n', ...
                         '物理深度：%+d um\n', ...
                         '原始PSF索引：%d\n', ...
                         '体积序号：%d\n', ...
                         '原始图像序号：%d\n', ...
                         '输入文件：%s\n', ...
                         '错误：%s\n\n%s\n'], ...
                        datasetName, ...
                        layerPosition, ...
                        physicalDepth, ...
                        originalPSFIndex, ...
                        frameLoop, ...
                        originalFrameIndex, ...
                        inputFileName, ...
                        ME.message, ...
                        getReport( ...
                            ME, ...
                            'extended', ...
                            'hyperlinks', ...
                            'off' ...
                        ) ...
                    );

                    writeTextFile( ...
                        errorFilePath, ...
                        errorText ...
                    );
                end
            end
        end

        %% ---------------- 判断任务是否成功 ---------------------------

        taskSuccessful = true;

        if runUniform && ...
                ~strcmp(uniformStatus, 'success')

            taskSuccessful = false;
        end

        if runTaylorVariance && ...
                ~strcmp(taylorStatus, 'success')

            taskSuccessful = false;
        end

        if runAllSingleFrames

            if singleFailedNum > 0
                taskSuccessful = false;
            end

            if singleSuccessNum ~= selectedFrameNum
                taskSuccessful = false;
            end
        end

        if taskSuccessful

            taskStatus = 'success';

            successTaskNum = ...
                successTaskNum + 1;

            completionText = sprintf( ...
                ['任务完成\n', ...
                 '数据集：%s\n', ...
                 '35层序号：%d\n', ...
                 '物理深度：%+d um\n', ...
                 '原始PSF索引：%d\n', ...
                 '迭代次数：%d\n', ...
                 '输入散斑光场图数量：%d\n', ...
                 '成功重建数量：%d\n', ...
                 '完成时间：%s\n'], ...
                datasetName, ...
                layerPosition, ...
                physicalDepth, ...
                originalPSFIndex, ...
                iterNum, ...
                selectedFrameNum, ...
                singleSuccessNum, ...
                char(datetime('now')) ...
            );

            writeTextFile( ...
                completedMarkerPath, ...
                completionText ...
            );

            fprintf( ...
                '\n当前数据集-深度任务全部完成。\n' ...
            );

        else

            taskStatus = 'failed';

            failedTaskNum = ...
                failedTaskNum + 1;

            fprintf(2, ...
                '\n当前数据集-深度任务没有完全成功。\n' ...
            );
        end

        %% ---------------- 写入日志 -----------------------------------

        if isempty(taskMessages)

            taskMessage = '';

        else

            taskMessage = strjoin( ...
                taskMessages, ...
                ' | ' ...
            );
        end

        taskEndTime = datetime('now');

        logCell(end + 1, :) = {
            datasetName, ...
            depthLoop, ...
            layerPosition, ...
            physicalDepth, ...
            originalPSFIndex, ...
            inputFrameNum, ...
            selectedFrameNum, ...
            uniformStatus, ...
            taylorStatus, ...
            singleSuccessNum, ...
            singleFailedNum, ...
            taskStatus, ...
            taskMessage, ...
            saveDepthRoot, ...
            char(taskStartTime), ...
            char(taskEndTime)
        };

        %% ---------------- 保存中间日志 -------------------------------

        saveLogSafely( ...
            logCell, ...
            saveRoot, ...
            logBaseName ...
        );
    end

    %% ---------------- 当前深度完成，清理内存 -------------------------

    clear H_use Ht_use CAindex_use;

    try
        g = gpuDevice;
        reset(g);

        fprintf( ...
            '\n当前深度处理完成，GPU 已 reset。\n' ...
        );

    catch
    end
end

%% ======================== 11. 保存最终日志 ==============================

logPath = saveLogSafely( ...
    logCell, ...
    saveRoot, ...
    logBaseName ...
);

mappingPath = fullfile( ...
    saveRoot, ...
    'all_100_volume_mapping_all_datasets.xlsx' ...
);

try
    writecell( ...
        mappingCell, ...
        mappingPath ...
    );

    fprintf( ...
        '\n总图像对应表已保存：\n%s\n', ...
        mappingPath ...
    );

catch ME

    warning( ...
        '总图像对应表保存失败：%s', ...
        ME.message ...
    );
end

%% ======================== 12. 最终统计 ==================================

fprintf('\n====================================================\n');
fprintf('全部重建结束。\n');

fprintf( ...
    '数据集数量：%d\n', ...
    length(datasetList) ...
);

fprintf( ...
    '选定深度数量：%d\n', ...
    length(selectedLayerPositions) ...
);

fprintf( ...
    '每个数据集预期散斑 LF 图数量：%d\n', ...
    expectedFrameNum ...
);

fprintf( ...
    '每张散斑 LF 图对应一个稀疏 8 层体积。\n' ...
);

fprintf( ...
    '每个数据集预期得到 100 个稀疏体积。\n' ...
);

fprintf( ...
    '三个数据集合计预期得到 300 个稀疏体积。\n' ...
);

fprintf( ...
    '成功的数据集-深度任务：%d\n', ...
    successTaskNum ...
);

fprintf( ...
    '失败的数据集-深度任务：%d\n', ...
    failedTaskNum ...
);

fprintf( ...
    '跳过的数据集-深度任务：%d\n', ...
    skippedTaskNum ...
);

fprintf( ...
    '输出根目录：\n%s\n', ...
    saveRoot ...
);

fprintf( ...
    '日志文件：\n%s\n', ...
    logPath ...
);

fprintf('====================================================\n');

end


%% ========================================================================
% 用 matfile 分段读取 H / Ht
%% ========================================================================
function [H_use, Ht_use, CAindex_use] = ...
    loadPSFByMatfileRuns( ...
        psfHPath, ...
        psfHtPath, ...
        depthIdxUse ...
    )

fprintf('原始 PSF 索引：');
fprintf('%d ', depthIdxUse);
fprintf('\n');

%% ------------------------- 读取 H ---------------------------------------

M_H = matfile(psfHPath);

H_use = readPSFByContinuousRuns( ...
    M_H, ...
    'H', ...
    depthIdxUse ...
);

clear M_H;

%% ------------------------- 读取 Ht --------------------------------------

M_Ht = matfile(psfHtPath);

Ht_use = readPSFByContinuousRuns( ...
    M_Ht, ...
    'Ht', ...
    depthIdxUse ...
);

%% ------------------------- 读取 CAindex ---------------------------------

CAindexAll = M_Ht.CAindex(:, :);

CAindex_use = ...
    CAindexAll(depthIdxUse, :);

clear M_Ht CAindexAll;

end


%% ========================================================================
% 按连续索引段读取 PSF
%% ========================================================================
function A = readPSFByContinuousRuns( ...
    M, ...
    varName, ...
    depthIdxUse ...
)

depthIdxUse = depthIdxUse(:)';

runCell = ...
    splitContinuousRuns(depthIdxUse);

A = [];

for r = 1:length(runCell)

    idxRun = runCell{r};

    fprintf( ...
        '  读取 %s：%d 到 %d，共 %d 层\n', ...
        varName, ...
        idxRun(1), ...
        idxRun(end), ...
        length(idxRun) ...
    );

    switch varName

        case 'H'

            temp = M.H( ...
                :, ...
                :, ...
                :, ...
                :, ...
                idxRun(1):idxRun(end) ...
            );

        case 'Ht'

            temp = M.Ht( ...
                :, ...
                :, ...
                :, ...
                :, ...
                idxRun(1):idxRun(end) ...
            );

        otherwise

            error( ...
                '未知 PSF 变量：%s', ...
                varName ...
            );
    end

    if ~isa(temp, 'single')
        temp = single(temp);
    end

    if isempty(A)

        A = temp;

    else

        A = cat( ...
            5, ...
            A, ...
            temp ...
        );
    end

    clear temp;
end

end


%% ========================================================================
% 把索引拆分成连续段
%% ========================================================================
function runCell = splitContinuousRuns(idx)

idx = idx(:)';

if isempty(idx)

    runCell = {};
    return;
end

breakPos = find(diff(idx) ~= 1);

startPos = [
    1, ...
    breakPos + 1 ...
];

endPos = [
    breakPos, ...
    length(idx) ...
];

runCell = cell( ...
    length(startPos), ...
    1 ...
);

for i = 1:length(startPos)

    runCell{i} = ...
        idx(startPos(i):endPos(i));
end

end


%% ========================================================================
% 获取图像列表
%% ========================================================================
function imgList = getImageList(folderPath)

imgList = [];

if ~exist(folderPath, 'dir')
    return;
end

imgList = [
    dir(fullfile(folderPath, '*.tif'));
    dir(fullfile(folderPath, '*.tiff'));
    dir(fullfile(folderPath, '*.bmp'));
    dir(fullfile(folderPath, '*.png'))
];

if isempty(imgList)
    return;
end

%% ------------------------- 去重 -----------------------------------------

fullNames = cell( ...
    length(imgList), ...
    1 ...
);

for i = 1:length(imgList)

    fullNames{i} = fullfile( ...
        imgList(i).folder, ...
        imgList(i).name ...
    );
end

[~, uniqueIdx] = unique( ...
    lower(string(fullNames)), ...
    'stable' ...
);

imgList = imgList(uniqueIdx);

%% ------------------------- 排序 -----------------------------------------

names = {imgList.name};

numbers = nan( ...
    length(names), ...
    1 ...
);

for k = 1:length(names)

    tokens = regexp( ...
        names{k}, ...
        '\d+', ...
        'match' ...
    );

    if ~isempty(tokens)

        numbers(k) = ...
            str2double(tokens{end});
    end
end

if all(~isnan(numbers))

    [~, sortIdx] = ...
        sort(numbers);

else

    [~, sortIdx] = sort( ...
        lower(string(names)) ...
    );
end

imgList = imgList(sortIdx);

end


%% ========================================================================
% 查找 uniform 图像
%% ========================================================================
function filePath = findUniformFile( ...
    folderPath, ...
    datasetName ...
)

filePath = '';

if ~exist(folderPath, 'dir')
    return;
end

candidateNames = {
    [datasetName, '_uniform.tif']
    [datasetName, '_uniform.tiff']
    'uniform.tif'
    'uniform.tiff'
    'uniform_img.tif'
    'uniform_img.tiff'
};

for i = 1:length(candidateNames)

    candidatePath = fullfile( ...
        folderPath, ...
        candidateNames{i} ...
    );

    if exist(candidatePath, 'file')

        filePath = candidatePath;
        return;
    end
end

candidateList = [
    dir(fullfile(folderPath, '*uniform*.tif'));
    dir(fullfile(folderPath, '*uniform*.tiff'))
];

if ~isempty(candidateList)

    filePath = fullfile( ...
        candidateList(1).folder, ...
        candidateList(1).name ...
    );
end

end


%% ========================================================================
% 查找 variance 图像
%
% 使用 *_var.tif。
% 不使用 *_sqrt.tif。
%% ========================================================================
function filePath = findVarianceFile( ...
    folderPath, ...
    datasetName ...
)

filePath = '';

if ~exist(folderPath, 'dir')
    return;
end

candidateNames = {
    [datasetName, '_var.tif']
    [datasetName, '_var.tiff']
    'var.tif'
    'var.tiff'
    'var_img.tif'
    'var_img.tiff'
};

for i = 1:length(candidateNames)

    candidatePath = fullfile( ...
        folderPath, ...
        candidateNames{i} ...
    );

    if exist(candidatePath, 'file')

        filePath = candidatePath;
        return;
    end
end

candidateList = [
    dir(fullfile(folderPath, '*var*.tif'));
    dir(fullfile(folderPath, '*var*.tiff'))
];

for i = 1:length(candidateList)

    candidateNameLower = ...
        lower(candidateList(i).name);

    if contains( ...
            candidateNameLower, ...
            'sqrt' ...
        )

        continue;
    end

    filePath = fullfile( ...
        candidateList(i).folder, ...
        candidateList(i).name ...
    );

    return;
end

end


%% ========================================================================
% 构建深度目录名称
%
% 示例：
%
% layer_01_depth_m340
% layer_20_depth_p040
%% ========================================================================
function folderName = makeDepthFolderName( ...
    layerPosition, ...
    physicalDepth ...
)

if physicalDepth < 0

    depthText = sprintf( ...
        'm%03d', ...
        abs(physicalDepth) ...
    );

else

    depthText = sprintf( ...
        'p%03d', ...
        physicalDepth ...
    );
end

folderName = sprintf( ...
    'layer_%02d_depth_%s', ...
    layerPosition, ...
    depthText ...
);

end


%% ========================================================================
% 确保目录存在
%% ========================================================================
function ensureFolder(folderPath)

if ~exist(folderPath, 'dir')
    mkdir(folderPath);
end

end


%% ========================================================================
% 在目录末尾添加文件分隔符
%% ========================================================================
function folderPathWithSep = ...
    addTrailingSeparator(folderPath)

folderPathWithSep = char(folderPath);

if isempty(folderPathWithSep)
    return;
end

if folderPathWithSep(end) ~= filesep

    folderPathWithSep = [
        folderPathWithSep, ...
        filesep ...
    ];
end

end


%% ========================================================================
% 获取带扩展名的文件名
%% ========================================================================
function fileName = ...
    getFileNameWithExtension(filePath)

[~, baseName, extension] = ...
    fileparts(filePath);

fileName = [
    baseName, ...
    extension ...
];

end


%% ========================================================================
% 写文本文件
%% ========================================================================
function writeTextFile( ...
    filePath, ...
    textContent ...
)

fid = fopen( ...
    filePath, ...
    'w' ...
);

if fid < 0

    warning( ...
        '无法创建文本文件：%s', ...
        filePath ...
    );

    return;
end

cleanupObj = onCleanup( ...
    @() fclose(fid) ...
); %#ok<NASGU>

fprintf( ...
    fid, ...
    '%s', ...
    textContent ...
);

end


%% ========================================================================
% 安全保存日志
%% ========================================================================
function savedLogPath = saveLogSafely( ...
    logCell, ...
    saveRoot, ...
    logBaseName ...
)

xlsxPath = fullfile( ...
    saveRoot, ...
    [logBaseName, '.xlsx'] ...
);

try

    writecell( ...
        logCell, ...
        xlsxPath ...
    );

    savedLogPath = xlsxPath;

    fprintf( ...
        '\n日志已保存：\n%s\n', ...
        savedLogPath ...
    );

catch ME

    warning( ...
        'Excel 日志保存失败：%s', ...
        ME.message ...
    );

    txtPath = fullfile( ...
        saveRoot, ...
        [logBaseName, '.txt'] ...
    );

    writeLogTxt( ...
        logCell, ...
        txtPath ...
    );

    savedLogPath = txtPath;

    fprintf( ...
        '\n日志已保存为 txt：\n%s\n', ...
        savedLogPath ...
    );
end

end


%% ========================================================================
% 保存 txt 日志
%% ========================================================================
function writeLogTxt( ...
    logCell, ...
    filePath ...
)

fid = fopen( ...
    filePath, ...
    'w' ...
);

if fid < 0

    warning( ...
        '无法创建日志：%s', ...
        filePath ...
    );

    return;
end

cleanupObj = onCleanup( ...
    @() fclose(fid) ...
); %#ok<NASGU>

for i = 1:size(logCell, 1)

    rowText = strings( ...
        1, ...
        size(logCell, 2) ...
    );

    for j = 1:size(logCell, 2)

        currentValue = ...
            logCell{i, j};

        if isempty(currentValue)

            rowText(j) = "";

        else

            rowText(j) = ...
                string(currentValue);
        end
    end

    fprintf( ...
        fid, ...
        '%s\n', ...
        strjoin( ...
            rowText, ...
            sprintf('\t') ...
        ) ...
    );
end

end